development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "login"
  user_name: "cucucity16@gmail.com"
  password: <%= ENV['EMAIL_PWD']%>
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "login"
  user_name: "cucucity16@gmail.com"
  password: <%= ENV['EMAIL_PWD']%>
  enable_starttls_auto: true